CREATE TABLE posts (
  id INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  title VARCHAR(25) DEFAULT NULL,
  short VARCHAR(50) DEFAULT NULL,
  description VARCHAR (255) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE articles (
  id INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  title VARCHAR(25) DEFAULT NULL,
  text VARCHAR (255) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;